/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.system.exitProcess

fun calcularRaices(a: Int, b: Int,c: Int) {
        for (x in -5..5) {
        val funcion = a*x*x + b*x + c
        println("El resultado cuando x es igual a $x: $funcion")
    }
}

fun discriminante(a: Int, b: Int,c: Int): Int{
    val disc= b*b-4*a*c
    println("El valor de la discriminante es $disc")
    return disc
}

fun raices(disc: Int,b: Int,a: Int){
    val raizDisc=Math.sqrt(disc.toDouble())
    val r1 : Double =(-b+raizDisc)/(2*a)
    println("La primera raíz es: ${"%.2f".format(r1)}")
    val r2 : Double =(-b-raizDisc)/(2*a)
    println("La segunda raíz es: ${"%.2f".format(r2)}")
}


fun main() {
    // Paso 1 crear funcion cuadratica
   val a=4
   val b=6
   val c=1 

   if(a<=0) {
        println ("a debe ser mayor a 0")
        exitProcess(0)
    }
    println("La función es $a x²+$b x+$c")

    // Paso 2 calcular funcion cuadratica
    calcularRaices(a,b,c)

    //Paso 3 calcular raices
    var valorDisc=discriminante(a,b,c)
    raices(valorDisc,b,a)


}
