/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.system.exitProcess

fun main() {
   val a=2
   val b=3
   val c=1 

   if(a<=0) {
        println ("a debe ser mayor a 0")
        exitProcess(0)
    }

    println("La función es $a x²+$b x+$c")
}
