/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.system.exitProcess

fun calcularRaices(a: Int, b: Int,c: Int) {
        for (x in -5..5) {
        val funcion = a*x*x + b*x + c
        println("El resultado cuando x es igual a $x: $funcion")
    }
}

fun discriminante(a: Int, b: Int,c: Int){
    val disc= b*b-4*a*c
    println("El valor de la discriminante es $disc")
}

fun raices(disc: Int,b: Int,a: Int){
    val raizDisc=Math.sqrt(disc)
    val r1=(-b+raizDisc)/(2*a)
    println("La primera raíz es: $r1")
    val r2=(-b-raizDisc)/(2*a)
    println("La segunda raíz es: $r2")
}


fun main() {
    // Paso 1 crear funcion cuadratica
   val a=2
   val b=3
   val c=1 

   if(a<=0) {
        println ("a debe ser mayor a 0")
        exitProcess(0)
    }
    println("La función es $a x²+$b x+$c")

    // Paso 2 calcular funcion cuadratica
    calcularRaices(2,3,1)

    //Paso 3 calcular raices
    discriminante(2,3,1)
    raices(1,3,2)


}
